# Generated by Django 4.2.4 on 2023-08-21 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_remove_transaction_amount_childtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="childtransaction",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
