# Generated by Django 4.2.4 on 2023-08-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_childtransaction_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="repeats",
            field=models.CharField(
                choices=[("once", "monthly")], default="once", max_length=60
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="childtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("debit", "Debit"), ("credit", "Credit")], max_length=60
            ),
        ),
    ]
