# Generated by Django 4.2.4 on 2023-08-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_transaction_amount_alter_transaction_repeats_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="childtransaction",
            name="title",
            field=models.CharField(default="bloop", max_length=50),
            preserve_default=False,
        ),
    ]
