# Generated by Django 4.2.4 on 2023-08-21 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0009_alter_childtransaction_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="childtransaction",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.account",
            ),
            preserve_default=False,
        ),
    ]
